# Generated by Django 4.2.25 on 2025-11-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Fashion - Men', 'Fashion - Men'), ('Fashion - Women', 'Fashion - Women'), ('Home & Kitchen', 'Home & Kitchen'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Books', 'Books'), ('Groceries & Gourmet', 'Groceries & Gourmet')], editable=False, max_length=100, null=True),
        ),
    ]
