# Generated by Django 4.2.25 on 2025-11-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_initial'),
        ('users', '0002_populate_preferred_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_preferred', to='storefront.category'),
        ),
    ]
