# Generated by Django 5.2.5 on 2025-11-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_admin_user_remove_user_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preferred_category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Fashion - Men', 'Fashion - Men'), ('Fashion - Women', 'Fashion - Women'), ('Home & Kitchen', 'Home & Kitchen'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Books', 'Books'), ('Groceries & Gourmet', 'Groceries & Gourmet')], max_length=100, null=True),
        ),
    ]
