# Generated by Django on 2025-11-14

from django.db import migrations

def populate_preferred_category_fk(apps, schema_editor):
    Customer = apps.get_model('users', 'Customer')
    Category = apps.get_model('storefront', 'Category')

    for c in Customer.objects.all():
        if c.preferred_category:
            try:
                c.preferred_category_fk = Category.objects.get(name=c.preferred_category)
                c.save()
            except Category.DoesNotExist:
                # You can log or ignore categories that don't exist
                print(f"No matching Category for '{c.preferred_category}'")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_preferred_category_fk'),  # update this to your latest users migration
        ('storefront', '0001_initial'),  # update to your latest storefront migration
    ]

    operations = [
        migrations.RunPython(populate_preferred_category_fk),
    ]
