# Generated by Django 4.2.25 on 2025-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_populate_preferred_category_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preferred_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
