# Generated by Django 4.2.25 on 2025-11-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_promotion_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='preferred_category',
        ),
    ]
