# Generated by Django 5.2.5 on 2025-12-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_aichatsession_aichatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
