# Generated by Django 5.2.5 on 2025-12-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_alter_aichatmessage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatsession',
            name='title',
        ),
    ]
