# Generated by Django 5.2.5 on 2025-12-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0007_remove_aichatsession_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Aurora Assistant')], max_length=10),
        ),
    ]
